#!/usr/bin/python

import sys
import socket


def terminate(host, port, ctrl_info):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((host, port))
    s.send(ctrl_info + '\0\0\0\0\0\0\0\0')
    s.close()



host = sys.argv[1]
port = int(sys.argv[2])
ctrl_info = sys.argv[3]

if len(sys.argv) >= 6:
    file_name = sys.argv[4]
    buffer_size = int(sys.argv[5])

    if len(sys.argv) == 7:
        wait_time = int(sys.argv[6])

else:
    terminate(host, port, ctrl_info)
